### ISSUE TITLE
Dynamic Values?

### ISSUE THREAD

**Issue by PeteMichaud** [karl257/dokuwiki-plugin-achart#1]
I see that the data must be static for security purposes, but I am using Docuwiki locally. It would be much more useful to me if I could call in arbitrary data, (eg. a web api), or embed template values (eg. loading the data from a locally uploaded csv file).

**Comment by karl257** [comment]
Sorry for this late reply. Look at develop branch which supports data from csv files and it still limited to some type of Charts like bar charts. Download https://github.com/karl257/dokuwiki-plugin-achart/archive/develop.zip and try

This an exemple of syntax to use :
```
<achart url=https://gist.github.com/karl257/6e799cc0d8a5e47ac11d97672a6890dc/raw/0a80ea7ff3b89d0f376aec0eff0d817550b32334/convertcsv.csv height=320px align=center>
{
  chart: {
      height: 350,
      type: 'bar',
  },
  dataLabels: {
      enabled: false
  },
  title: {
      text: "From external url",
  }
}
</achart>

<achart url=:exemple:convertcsv.csv height=320px align=center>
{
  chart: {
      height: 350,
      type: 'bar',
  },
  dataLabels: {
      enabled: false
  },
  title: {
      text: "From a local file",
  }
}
</achart>
```

**Comment by TheRaven500** [comment]
Sorry for hijaking this issue, but local file does not work for me.
Should it work with the actuel (official) plugin or do i need a develop build?

**Comment by karl257** [comment]
Now the plugin has been updated

**Comment by TheRaven500** [comment]
I have updated and tested the new plugin. Now i get a red bar "Chart cannot be displayed ! Requested local CSV file does not exist".

**Comment by karl257** [comment]
If it's remote data check if you give the full URL. If not, the external file are reconignized as internal.
